import { useEffect, useState } from "react";
import { API_BASE_URL } from "../../services/api";
import type { RunResponse } from "../../types";

type Test = { test_id: string; category: string; passed: boolean };
type Entry = {
  kind: string;
  data: {
    model?: string;
    provider?: string;
    latency_ms?: number;
    dseq?: string;
    closed?: boolean;
    message?: string;
    source_sha256?: string;
    request_id?: string;
    challenges?: {
      id: string;
      family: string;
      rationale: string;
      actions: unknown[];
    }[];
    results?: { name: string; source_sha256: string; tests: Test[] }[];
  };
};
type Detail = {
  run_id: string;
  source: string;
  execution_mode: string;
  entries: Entry[];
  budget: { reserved_usd?: number; cap_usd?: number };
};

export function WorkspaceEvidence({ run }: { run: RunResponse }) {
  const [detail, setDetail] = useState<Detail | null>(null);
  const [error, setError] = useState(false);
  useEffect(() => {
    const controller = new AbortController();
    let timer: ReturnType<typeof setTimeout>;
    const poll = async () => {
      try {
        const response = await fetch(
          `${API_BASE_URL}/api/runs/${encodeURIComponent(run.run_id)}/execution`,
          { signal: controller.signal, cache: "no-store" },
        );
        if (!response.ok) throw Error();
        const value = (await response.json()) as Detail;
        if (
          value.run_id !== run.run_id ||
          value.source !== "execution" ||
          !Array.isArray(value.entries)
        )
          throw Error();
        if (!controller.signal.aborted) {
          setDetail(value);
          setError(false);
        }
      } catch {
        if (!controller.signal.aborted) setError(true);
      }
      if (
        !controller.signal.aborted &&
        !["verified", "rejected", "inconclusive", "error"].includes(run.status)
      )
        timer = setTimeout(poll, 2000);
    };
    void poll();
    return () => {
      controller.abort();
      clearTimeout(timer);
    };
  }, [run.run_id, run.status]);
  const entries = detail?.entries ?? [];
  const models = entries.filter((e) => e.kind === "akashml_challenges");
  const executions = entries.filter((e) => e.data.results);
  const lifecycle = entries.filter((e) =>
    /^akash_(deploying|starting|testing|closing|closed)$/.test(e.kind),
  );
  const provenance = entries.find((e) => e.kind === "generation_provenance");
  return (
    <section
      className="workspace-evidence"
      aria-label="Workspace execution evidence"
    >
      <div className="evidence-section-heading">
        <div>
          <span className="section-label">Executed evidence</span>
          <h2>Challenges and execution locations</h2>
        </div>
        <span>
          {detail?.execution_mode === "local_akash"
            ? "Local + Akash"
            : "Local verification"}
        </span>
      </div>
      {error && (
        <p role="status">
          Execution details are unavailable. No additional result is inferred.
        </p>
      )}
      {!detail && !error && <p>Loading execution evidence…</p>}
      {provenance && (
        <p className="action-help">
          Original generated by {provenance.data.model}. Its source and
          generation receipt were preserved before the audit.
        </p>
      )}
      {lifecycle.length > 0 && (
        <ol className="cloud-progress">
          {lifecycle.map((e, i) => (
            <li key={i}>
              <strong>{e.kind.replace("akash_", "")}</strong>
              {e.data.dseq && <span>Deployment {e.data.dseq}</span>}
            </li>
          ))}
        </ol>
      )}
      <div className="workspace-matrix">
        {executions.map((e, i) => (
          <article key={i}>
            <span className="section-label">
              {e.kind === "akash_tests" ? "Akash compute" : "Local container"}
            </span>
            {e.data.results?.map((r) => (
              <div className="execution-count" key={r.name}>
                <strong>
                  {r.tests.filter((t) => t.passed).length}/{r.tests.length}
                </strong>
                <span>
                  {r.name === "patched" && !run.patch
                    ? "Same revision · cloud comparison"
                    : r.name}{" "}
                  checks passed
                </span>
              </div>
            ))}
            {e.data.closed && <p>Deployment closure confirmed.</p>}
            <details>
              <summary>Inspect individual checks</summary>
              {e.data.results?.map((r) => (
                <ul key={r.name}>
                  {r.tests.map((t) => (
                    <li key={t.test_id}>
                      {t.passed ? "Pass" : "Fail"} · {t.test_id}
                    </li>
                  ))}
                </ul>
              ))}
            </details>
          </article>
        ))}
      </div>
      {models.map((entry, i) => (
        <div className="challenge-generation" key={i}>
          <h3>AkashML challenge set {i + 1}</h3>
          <p className="action-help">
            {entry.data.model} ·{" "}
            {entry.data.latency_ms
              ? `${(entry.data.latency_ms / 1000).toFixed(1)}s inference`
              : "Inference recorded"}{" "}
            · expected outcomes defined by the trusted policy
          </p>
          {entry.data.challenges?.map((c) => (
            <details key={c.id}>
              <summary>
                {c.family.replaceAll("_", " ")} · {c.actions.length} actions
              </summary>
              <p>{c.rationale}</p>
              <pre>{JSON.stringify(c.actions, null, 2)}</pre>
            </details>
          ))}
        </div>
      ))}
      {detail?.budget.cap_usd !== undefined && (
        <p className="action-help">
          Validation budget: ${detail.budget.reserved_usd?.toFixed(2)}{" "}
          conservatively reserved of ${detail.budget.cap_usd}. Reservations are
          not measured charges.
        </p>
      )}
      <p className="action-help">
        Remote verification uses containers. Provider-host integrity is trusted;
        no hardware attestation is claimed.
      </p>
    </section>
  );
}
