/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics */
        get: operations["analytics_api_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audio/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audio */
        get: operations["get_audio_api_audio__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Briefing */
        get: operations["get_briefing_api_runs__run_id__briefing_get"];
        put?: never;
        /** Create Briefing */
        post: operations["create_briefing_api_runs__run_id__briefing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Challenge */
        post: operations["challenge_api_runs__run_id__challenge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsResponse */
        AnalyticsResponse: {
            /** Failure Patterns */
            failure_patterns: components["schemas"]["FailurePattern"][];
            /** Rejected Count */
            rejected_count: number;
            /** Run Count */
            run_count: number;
            source: components["schemas"]["Source"];
            /** Verified Count */
            verified_count: number;
        };
        /** BaselineResult */
        BaselineResult: {
            /** Observed Status */
            observed_status?: number | null;
            /** Reproduced */
            reproduced: boolean;
        };
        /**
         * BriefingRequest
         * @description Only the expected evidence identity, never arbitrary narration text.
         */
        BriefingRequest: {
            /** Report Sha256 */
            report_sha256: string;
        };
        /** BriefingResponse */
        BriefingResponse: {
            /** Artifact Id */
            artifact_id?: string | null;
            /** Audio Path */
            audio_path?: string | null;
            /** Report Sha256 */
            report_sha256: string;
            /** Run Id */
            run_id: string;
            /**
             * Source
             * @default execution
             * @constant
             */
            source: "execution";
            /**
             * Status
             * @enum {string}
             */
            status: "unavailable" | "not_generated" | "generating" | "ready" | "error";
            /** Transcript */
            transcript?: string | null;
        };
        /** ChallengeRequest */
        ChallengeRequest: {
            /**
             * Max Challenges
             * @default 2
             */
            max_challenges: number;
            /** Policy Ids */
            policy_ids?: string[];
        };
        /** ChallengeResponse */
        ChallengeResponse: {
            /** Run Id */
            run_id: string;
            /**
             * Source
             * @default execution
             * @constant
             */
            source: "execution";
            /**
             * Status
             * @default challenging
             * @constant
             */
            status: "challenging";
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /**
             * Max Attempts
             * @default 3
             */
            max_attempts: number;
            /**
             * Target
             * @constant
             */
            target: "LedgerLite";
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "not_implemented" | "not_found" | "invalid_request" | "conflict" | "internal_error";
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * EventSeverity
         * @enum {string}
         */
        EventSeverity: "info" | "warning" | "error" | "critical";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "stage_started" | "stage_completed" | "finding_discovered" | "baseline_reproduced" | "patch_proposed" | "patch_applied" | "test_completed" | "challenge_proposed" | "retry_scheduled" | "run_completed" | "run_failed";
        /** EventsResponse */
        EventsResponse: {
            /** Events */
            events: components["schemas"]["SecurityEvent"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Run Id */
            run_id: string;
            source: components["schemas"]["Source"];
        };
        /** EvidenceReference */
        EvidenceReference: {
            /** Artifact Id */
            artifact_id: string;
            /** Description */
            description: string;
            /** Sha256 */
            sha256: string;
        };
        /** FailurePattern */
        FailurePattern: {
            /** Challenge Family */
            challenge_family: string;
            /** Executions */
            executions: number;
            /** Failures */
            failures: number;
        };
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            severity: components["schemas"]["FindingSeverity"];
            /** Title */
            title: string;
        };
        /**
         * FindingSeverity
         * @enum {string}
         */
        FindingSeverity: "info" | "low" | "medium" | "high" | "critical";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Service
             * @default proofloop
             * @constant
             */
            service: "proofloop";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        JsonValue: unknown;
        /** PatchProposal */
        PatchProposal: {
            /** Attempt */
            attempt: number;
            /** Diff */
            diff: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Evidence */
            evidence?: components["schemas"]["EvidenceReference"][];
            /** Limitations */
            limitations: string[];
            /** Run Id */
            run_id: string;
            source: components["schemas"]["Source"];
            status: components["schemas"]["RunStatus"];
            /** Summary */
            summary: string;
            verification?: components["schemas"]["VerificationSummary"] | null;
        };
        /** RunResponse */
        RunResponse: {
            baseline?: components["schemas"]["BaselineResult"] | null;
            /** Events */
            events?: components["schemas"]["SecurityEvent"][];
            finding?: components["schemas"]["Finding"] | null;
            patch?: components["schemas"]["PatchProposal"] | null;
            /** Run Id */
            run_id: string;
            source: components["schemas"]["Source"];
            status: components["schemas"]["RunStatus"];
            /** Target */
            target: string;
            verification?: components["schemas"]["VerificationSummary"] | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "discovering" | "reproducing" | "generating_patch" | "applying_patch" | "verifying" | "challenging" | "retrying" | "verified" | "rejected" | "inconclusive" | "error";
        /** SecurityEvent */
        SecurityEvent: {
            /** Event Id */
            event_id: string;
            event_type: components["schemas"]["EventType"];
            /** Message */
            message: string;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Run Id */
            run_id: string;
            severity: components["schemas"]["EventSeverity"];
            source: components["schemas"]["Source"];
            stage: components["schemas"]["RunStatus"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * Source
         * @enum {string}
         */
        Source: "fixture" | "execution";
        /** VerificationSummary */
        VerificationSummary: {
            /** Adversarial Passed */
            adversarial_passed: number;
            /** Adversarial Total */
            adversarial_total: number;
            /** Functional Passed */
            functional_passed: number;
            /** Functional Total */
            functional_total: number;
            /** Security Passed */
            security_passed: number;
            /** Security Total */
            security_total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analytics_api_analytics_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PLANNED: engine/integration not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_audio_api_audio__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PLANNED: engine/integration not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PLANNED: engine/integration not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PLANNED: engine/integration not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_briefing_api_runs__run_id__briefing_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PLANNED: engine/integration not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_briefing_api_runs__run_id__briefing_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PLANNED: engine/integration not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    challenge_api_runs__run_id__challenge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PLANNED: engine/integration not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PLANNED: engine/integration not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_report_api_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PLANNED: engine/integration not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
